### ISSUE TITLE
Fails to build on OSX

### ISSUE THREAD

**Issue by skeldoy** [chrisdew/protobuf#55]
OS: 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu3789.41.3~3/RELEASE_X86_64 x86_64
npm: 4.3.0
node: v7.6.0

Apart from a shitload of warning about for-looping over and comparing integers and unsigned long.. There is those pesky error-messages that stops the whole thing:

../protobuf/src/google/protobuf/message.cc:130:60: error: implicit instantiation of undefined template
      'std::__1::basic_istream<char, std::__1::char_traits<char> >'
  return ParseFromZeroCopyStream(&zero_copy_input) && input->eof();
                                                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:109:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_istream;
                                ^
../protobuf/src/google/protobuf/message.cc:135:67: error: implicit instantiation of undefined template
      'std::__1::basic_istream<char, std::__1::char_traits<char> >'
  return ParsePartialFromZeroCopyStream(&zero_copy_input) && input->eof();
                                                                  ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:109:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_istream;
                                ^
../protobuf/src/google/protobuf/message.cc:175:16: error: implicit instantiation of undefined template
      'std::__1::basic_ostream<char, std::__1::char_traits<char> >'
  return output->good();
               ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iosfwd:111:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_ostream;

**Comment by syndbg** [comment]
#56
